### ISSUE TITLE
Releasing panics with "cannot access key version"

### ISSUE THREAD

**Issue by Michael-F-Bryan** [sunng87/cargo-release#274]
I'm trying to release a new version of [`include_dir`](https://github.com/Michael-F-Bryan/include_dir) and was running into an unexpected panic on [this line](https://github.com/sunng87/cargo-release/blob/84bbfd888e976c21cc3f424a4c8ed3dbfa048ef9/src/cargo.rs#L142).

Reinstalling with a debug build yields this backtrace:

```console
$ RUST_BACKTRACE=1 cargo release --sign patch
Release include_dir_impl 0.6.1? [y/N]
y
[2021-06-30T17:38:47Z INFO ] Update include_dir_impl to version 0.6.1
[2021-06-30T17:38:47Z INFO ] Fixing include_dir's dependency on include_dir_impl to `= 0.6.1` (from `= 0.6.0`)
thread 'main' panicked at 'cannot access key version', /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/toml_edit-0.2.1/src/index.rs:84:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/std/src/panicking.rs:457:5
   2: <str as toml_edit::index::Index>::index_or_insert
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/toml_edit-0.2.1/src/index.rs:84:18
   3: <&T as toml_edit::index::Index>::index_or_insert
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/toml_edit-0.2.1/src/index.rs:106:9
   4: toml_edit::index::<impl core::ops::index::IndexMut<I> for toml_edit::table::Item>::index_mut
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/toml_edit-0.2.1/src/index.rs:127:9
   5: cargo_release::cargo::set_dependency_version
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-release-0.15.1/src/cargo.rs:142:17
   6: cargo_release::update_dependent_versions
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-release-0.15.1/src/main.rs:348:29
   7: cargo_release::release_packages
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-release-0.15.1/src/main.rs:610:13
   8: cargo_release::release_workspace
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-release-0.15.1/src/main.rs:437:5
   9: cargo_release::main
             at /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-release-0.15.1/src/main.rs:1113:11
  10: core::ops::function::FnOnce::call_once
             at /rustc/a435b49e86d16e98dcc6595dd471f95e823f41aa/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Do you have any suggestions for I can work around this in the meantime?

CC: https://github.com/Michael-F-Bryan/include_dir/issues/58

**Comment by Michael-F-Bryan** [comment]
I figured it out. The `include_dir` crate was depending on `include_dir_impl = "=0.6.0"` (i.e. *just* crates.io) when we should be using path dependencies during development and crates.io in production.

I was able to fix this on my side with https://github.com/Michael-F-Bryan/include_dir/commit/87f172efb7400ba5d58e6291ff419c5b5f6871db, but there should probably be a check in `cargo release` to avoid the panic.

```diff
diff --git a/include_dir/Cargo.toml b/include_dir/Cargo.toml
index d41763e..d555176 100644
--- a/include_dir/Cargo.toml
+++ b/include_dir/Cargo.toml
@@ -25,7 +25,7 @@ repository = "Michael-F-Bryan/include_dir"
 [dependencies]
 glob = { version = "0.3", optional = true }
 proc-macro-hack = "0.5"
-include_dir_impl = "=0.6.0"
+include_dir_impl = { version = "=0.6.1-alpha.0", path = "../include_dir_impl" }

 [dev-dependencies]
 tempdir = "0.3"
```
